import * as React from "react";
import type { SVGProps } from "react";
const SvgFtdi = (props: SVGProps<SVGSVGElement>) => (
  <g xmlns="http://www.w3.org/2000/svg"
    width={103.899}
    height={57.6}
    baseProfile="tiny"
    viewBox="0 0 77.924 43.2"
    {...props}

    transform={`translate(${props.x || 0}, ${props.y || 0}), scale(1), rotate(${props.rotate || 0})`}
  >
    <desc>{"Fritzing breadboard generated by brd2svg"}</desc>
    <g strokeWidth={0}

    >
      <path
        fill="#C62717"
        d="M0 0h75.6v43.2H0zm59.924 27.836a1.276 1.276 0 1 0 2.552 0 1.276 1.276 0 1 0-2.552 0m0-12.472a1.276 1.276 0 1 0 2.552 0 1.276 1.276 0 1 0-2.552 0M5.76 39.6a1.44 1.44 0 1 0 2.88 0 1.44 1.44 0 1 0-2.88 0m0-7.2a1.44 1.44 0 1 0 2.88 0 1.44 1.44 0 1 0-2.88 0m0-7.2a1.44 1.44 0 1 0 2.88 0 1.44 1.44 0 1 0-2.88 0m0-7.2a1.44 1.44 0 1 0 2.88 0 1.44 1.44 0 1 0-2.88 0m0-7.2a1.44 1.44 0 1 0 2.88 0 1.44 1.44 0 1 0-2.88 0m0-7.2a1.44 1.44 0 1 0 2.88 0 1.44 1.44 0 1 0-2.88 0"
      />
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 17.1 3.78)"
      >
        {"VCC"}
      </text>
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 20.7 7.38)"
      >
        {"TXO"}
      </text>
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 24.3 10.98)"
      >
        {"RXI"}
      </text>
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 10.08 -3.24)"
      >
        {"GND"}
      </text>
      <text x={46.8} y={4.32} fill="#fff" fontFamily="OCRA" fontSize={3.341}>
        {"FTDI Basic"}
      </text>
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 27.9 14.58)"
      >
        {"DTR"}
      </text>
      <text x={29.88} y={8.64} fill="#fff" fontFamily="OCRA" fontSize={3.341}>
        {"RX"}
      </text>
      <text x={22.68} y={8.64} fill="#fff" fontFamily="OCRA" fontSize={3.341}>
        {"TX"}
      </text>
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 13.5 .18)"
      >
        {"CTS"}
      </text>
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 5.22 1.62)"
      >
        {"BLK"}
      </text>
      <text
        fill="#fff"
        fontFamily="OCRA"
        fontSize={2.673}
        transform="rotate(-90 23.04 19.44)"
      >
        {"GRN"}
      </text>
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeWidth={0.576}
        d="M39.285 41.922h-4.252M35.033 41.922v-6.804M35.033 35.118h4.252M44.955 41.922h3.118M48.073 41.922l1.134-1.134M49.207 40.788v-4.536M49.207 36.252l-1.134-1.134M48.073 35.118h-3.118"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeWidth={0.576}
        d="M25.682 4.904V3.6M25.682 2.296V3.6M25.682 3.6l-.879.879M25.71 3.6l-.907-.907M24.803 2.693v1.786"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeWidth={0.576}
        d="M31.918 2.296V3.6M31.918 4.904V3.6M31.918 3.6l.879-.879M31.89 3.6l.907.907M32.797 4.507V2.721"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeWidth={0.576}
        d="M21.852 35.325h4.536"
      />
      <path
        fill="none"
        stroke="#fff"
        strokeWidth={0.576}
        d="M21.285 40.144a.72.72 0 0 0 .567.85M26.388 40.995a.723.723 0 0 0 .567-.85M26.955 36.176a.723.723 0 0 0-.567-.85M21.852 35.325a.72.72 0 0 0-.567.85"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeWidth={0.576}
        d="M26.388 40.995h-4.536"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeWidth={0.432}
        d="M17.66 13.309h29.48M47.14 13.309v16.582M47.14 29.891H17.66M17.66 29.891V13.309"
      />
      <circle
        cx={20.424}
        cy={27.128}
        r={1.303}
        fill="none"
        stroke="#fff"
        strokeWidth={0.432}
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeWidth={0.576}
        d="M64.885 32.372h-5.953M51.846 30.387v-2.551M51.846 15.364v-2.551M58.932 10.828h5.953"
      />
      <path fill="#333" d="M35.033 35.118h14.173v6.803H35.033z" />
      <path
        fill="#fff"
        fillOpacity={0.15}
        d="M24.803 2.296h.907v2.608h-.907zM31.89 2.296h.907v2.608h-.907zM21.271 35.325h5.698v5.669h-5.698z"
      />
      <path fill="#333" d="M17.66 13.309h29.48v16.583H17.66z" />
      <circle
        cx={7.2}
        cy={39.6}
        r={1.872}
        fill="none"
        stroke="#9A916C"
        strokeWidth={0.864}
        data-pin="DTR"
      />
      <circle
        cx={7.2}
        cy={32.4}
        r={1.872}
        fill="none"
        stroke="#9A916C"
        strokeWidth={0.864}
        data-pin="RX"
      />
      <circle
        cx={7.2}
        cy={25.2}
        r={1.872}
        fill="none"
        stroke="#9A916C"
        strokeWidth={0.864}
        data-pin="TX"
      />
      <circle
        cx={7.2}
        cy={18}
        r={1.872}
        fill="none"
        stroke="#9A916C"
        strokeWidth={0.864}
        data-pin="POWER"
      />
      <circle
        cx={7.2}
        cy={10.8}
        r={1.872}
        fill="none"
        stroke="#9A916C"
        strokeWidth={0.864}
        data-pin="CTS"
      />
      <circle
        cx={7.2}
        cy={3.6}
        r={1.872}
        fill="none"
        stroke="#9A916C"
        strokeWidth={0.864}
        data-pin="GND"
      />
      <path fill="#404040" d="M11.175-.008v43.2H3.976v-43.2z" />
      <path d="M8.966 2.202v2.781H6.184v-2.78z" />
      <path fill="#2A2A29" d="M9.991 1.177 8.966 2.2v2.784L9.991 6.01z" />
      <path fill="#474747" d="M9.991 6.01 8.963 4.983h-2.78L5.158 6.01z" />
      <path fill="#595959" d="m5.16 6.008 1.022-1.025V2.2L5.16 1.177z" />
      <path fill="#373737" d="M5.16 1.175 6.183 2.2h2.782l1.025-1.025z" />
      <path d="M8.966 9.403v2.781H6.184v-2.78z" />
      <path fill="#2A2A29" d="M9.991 8.376 8.966 9.4v2.783l1.025 1.025z" />
      <path fill="#474747" d="m9.991 13.208-1.028-1.025h-2.78l-1.024 1.025z" />
      <path fill="#595959" d="m5.16 13.207 1.022-1.025V9.4L5.16 8.376z" />
      <path fill="#373737" d="M5.16 8.374 6.183 9.4h2.782l1.025-1.026z" />
      <path d="M8.966 16.602v2.781H6.184v-2.78z" />
      <path fill="#2A2A29" d="M9.991 15.576 8.966 16.6v2.784l1.025 1.025z" />
      <path fill="#474747" d="m9.991 20.41-1.028-1.026h-2.78L5.158 20.41z" />
      <path fill="#595959" d="m5.16 20.408 1.022-1.025V16.6L5.16 15.576z" />
      <path fill="#373737" d="M5.16 15.575 6.183 16.6h2.782l1.025-1.025z" />
      <path d="M8.966 23.803v2.781H6.184v-2.78z" />
      <path fill="#2A2A29" d="m9.991 22.777-1.025 1.024v2.783l1.025 1.025z" />
      <path fill="#474747" d="m9.991 27.61-1.028-1.026h-2.78L5.158 27.61z" />
      <path fill="#595959" d="m5.16 27.608 1.022-1.026v-2.78L5.16 22.776z" />
      <path fill="#373737" d="m5.16 22.774 1.024 1.027h2.782l1.025-1.027z" />
      <path d="M8.966 31.002v2.781H6.184v-2.78z" />
      <path fill="#2A2A29" d="M9.991 29.977 8.966 31v2.784l1.025 1.025z" />
      <path fill="#474747" d="m9.991 34.81-1.028-1.026h-2.78L5.158 34.81z" />
      <path fill="#595959" d="m5.16 34.807 1.022-1.024V31L5.16 29.977z" />
      <path fill="#373737" d="M5.16 29.975 6.183 31h2.782l1.025-1.025z" />
      <path d="M8.966 38.202v2.781H6.184v-2.78z" />
      <path fill="#2A2A29" d="M9.991 37.176 8.966 38.2v2.784l1.025 1.024z" />
      <path fill="#474747" d="m9.991 42.008-1.028-1.024h-2.78l-1.024 1.024z" />
      <path fill="#595959" d="m5.16 42.008 1.022-1.025V38.2L5.16 37.176z" />
      <path fill="#373737" d="M5.16 37.174 6.183 38.2h2.782l1.025-1.026z" />
      <g fill="#8D8C8C"

      >
        <path d="M57.905 37.423h-6.254V30.83h6.254zM70.994 37.423h-7.238V30.83h7.238z" />
      </g>
      <g fill="#8D8C8C"

      >
        <path d="M57.905 12.39h-6.254V5.795h6.254zM70.994 12.39h-7.238V5.795h7.238z" />
      </g>
      <path
        fill="#404040"
        d="m54.238 17.409-1.086.825v-6.269h-.954v19.35h.954V24.99l1.086.827v6.47h22.625V10.94H54.238z"
      />
      <path d="M63.187 26.158c0-.156.127-.271.28-.255l10.496 1.096a.32.32 0 0 1 .281.312v1.743a.32.32 0 0 1-.28.312l-10.497 1.099a.25.25 0 0 1-.28-.254v-.256a.32.32 0 0 1 .28-.31l9.542-.83a.313.313 0 0 0 .281-.308v-.65a.32.32 0 0 0-.28-.31l-9.543-.828a.315.315 0 0 1-.28-.31zM63.187 13.015c0-.152.127-.27.28-.255l10.497 1.101a.324.324 0 0 1 .281.312v1.742a.32.32 0 0 1-.28.312l-10.498 1.099a.25.25 0 0 1-.28-.254v-.257c0-.155.126-.295.28-.312l9.542-.828a.313.313 0 0 0 .281-.311v-.646a.325.325 0 0 0-.28-.312l-9.543-.825a.316.316 0 0 1-.28-.312z" />
      <path fill="none" d="M73.284 15.653v-1.218l-.828-.071v1.353z" />
      <path fill="#939393" d="m72.456 14.364.828.071v1.218l-.828.064z" />
      <path fill="#545454" d="m72.456 14.364-.349-.032v1.423l.35-.038z" />
      <path fill="none" d="M73.284 28.796v-1.223l-.828-.068v1.355z" />
      <path fill="#939393" d="m72.456 27.505.828.068v1.223l-.828.064z" />
      <path fill="#545454" d="m72.456 27.505-.349-.035v1.427l.35-.037z" />
      <path fill="#939393" d="M66.729 24.52h-2.014v-5.556h2.014z" />
      <path fill="#545454" d="M64.716 24.52h-1.115v-5.556h1.115z" />
      <path d="M75.2 24.856a.306.306 0 0 0-.282-.301l-11.605-.7a.31.31 0 0 1-.282-.3v-3.89c0-.154.128-.29.282-.304l11.605-.69a.306.306 0 0 0 .282-.302v-.519a.27.27 0 0 0-.282-.267l-13.192.96a.315.315 0 0 0-.283.309v5.519a.32.32 0 0 0 .283.309l13.193.956a.26.26 0 0 0 .282-.263z" />
      <path fill="none" d="M54.834 31.656h21.717" />
      <path
        fill="none"
        stroke="#FFF"
        strokeLinecap="round"
        strokeOpacity={0.15}
        strokeWidth={0.5}
        d="M54.834 11.313h21.717"
      />
      <path fill="none" d="M53.264 24.308V18.92" />
    </g>
  </g>
);
export default SvgFtdi;
