import * as React from "react";
import type { SVGProps } from "react";
const SvgNrf24L01 = (props: SVGProps<SVGSVGElement>) => (
  <g
    xmlSpace="preserve"
    width={126.918}
    height={63}
    viewBox="0 0 95.188 47.25"
    {...props}
    transform={`translate(${props.x || 0}, ${props.y || 0}), scale(1), rotate(${props.rotate || 0})`}
  >
    <g transform="translate(27.638 21.633)">
      <desc>{"Fritzing breadboard generated by brd2svg"}</desc>
      <path
        fill="#025610"
        d="M-27.638 25.617H67.55v-47.25h-95.188zM61.515 5.946a1.44 1.44 0 1 1 2.879-.001 1.44 1.44 0 0 1-2.879.001m0-7.2a1.44 1.44 0 0 1 2.88 0 1.44 1.44 0 0 1-2.88 0m.084 21.55a1.44 1.44 0 1 1 2.879 0 1.44 1.44 0 0 1-2.879 0m0-7.202a1.44 1.44 0 0 1 2.878 0 1.44 1.44 0 0 1-2.878 0m-5.736 8.56a1.44 1.44 0 0 1 0-2.878 1.44 1.44 0 0 1 0 2.878M54.29 5.945a1.44 1.44 0 1 1 2.879-.001 1.44 1.44 0 0 1-2.879.001m0-7.2a1.44 1.44 0 0 1 2.88 0 1.44 1.44 0 0 1-2.88 0m.084 14.349a1.44 1.44 0 0 1 2.878 0 1.44 1.44 0 0 1-2.878 0"
      />
      <path fill="#A0A0A0" d="M7.853-19.613h38.863v8.346H7.853z" />
      <circle
        cx={63.101}
        cy={-1.395}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="MISO"
      />
      <circle
        cx={63.101}
        cy={5.758}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="SCK"
      />
      <circle
        cx={63.101}
        cy={12.953}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="CE"
      />
      <circle
        cx={63.101}
        cy={20.155}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="GND"
      />
      <path
        fill="#FFF"
        fillOpacity={0.15}
        d="M31.68 16.3h2.886v7.709H31.68zM36.395 16.3h2.886v7.709h-2.886zM41.14 16.3h2.886v7.709H41.14zM46.077 16.3h2.886v7.709h-2.886zM25.87-5.157h7.707v2.886H25.87z"
      />
      <path fill="#333" d="M25.869.657h13.607V12.64H25.869z" />
      <path
        fill="#FFF"
        fillOpacity={0.15}
        d="M-1.337-3.566h7.708v2.885h-7.708zM-1.337-8.504h7.708v2.886h-7.708z"
      />
      <circle
        cx={55.745}
        cy={-1.395}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="IRQ"
      />
      <circle
        cx={55.745}
        cy={5.758}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="MOSI"
      />
      <circle
        cx={55.745}
        cy={12.953}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="CSN"
      />
      <circle
        cx={55.745}
        cy={20.155}
        r={2.052}
        fill="none"
        stroke="#9A916C"
        strokeWidth={1.224}
        data-pin="VCC"
      />
      <path
        fill="#FFF"
        fillOpacity={0.15}
        d="M-1.337-19.254h7.708v2.886h-7.708zM-1.337 11.198h7.708v2.885h-7.708zM-1.337 1.163h7.708v2.886h-7.708zM9.16 6.648h2.885v7.708H9.16zM9.159-3.197h2.886v7.708H9.159zM14.096 1.502h2.887V9.21h-2.887zM53.453-14.153h7.707v2.886h-7.707z"
      />
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(46.35 12.954)"
      >
        {"CE"}
      </text>
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(46.35 20.156)"
      >
        {"GND"}
      </text>
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(46.35 6.034)"
      >
        {"SCK"}
      </text>
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(46.35 -.34)"
      >
        {"MISO"}
      </text>
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(38.296 20.156)"
      >
        {"VCC"}
      </text>
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(38.296 12.941)"
      >
        {"CSN"}
      </text>
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(38.296 5.759)"
      >
        {"MOSI"}
      </text>
      <text
        fill="#FFF"
        fontFamily="Droid Sans"
        fontSize={2.944}
        transform="translate(38.296 -.34)"
      >
        {"IRQ"}
      </text>
      <path
        fill="none"
        stroke="#7A7838"
        d="M-24.7.954h15.917M-24.7 12.954h22.75M-24.7 6.954h15.916M-24.699-16.837h15.916M-24.699-4.837h15.916M-24.699-10.837h15.916M-24.2-16.837v6.014M-9.262-10.867v6.026M-24.2-4.837v6.014M-24.2 6.954v6.015M-9.262 1.036v6.026M-5.575-20.1v33.61"
      />
    </g>
  </g>
);
export default SvgNrf24L01;
