import { lazy } from "react";

export const componentsList = {
    "esp32-devkit-v1": lazy(() => import("./elements/Esp32DevkitV1")),
    "arduino-uno": lazy(() => import("./elements/ArduinoUno")),
    "buzzer": lazy(() => import("./elements/Buzzer")),
    "analog-joystick": lazy(() => import("./elements/AnalogJoystick")),
    "ds1307": lazy(() => import("./elements/Ds1307")),
    "flame-sensor": lazy(() => import("./elements/FlameSensor")),
    "franzininho": lazy(() => import("./elements/Franzininho")),
    "gas-sensor": lazy(() => import("./elements/GasSensor")),
    "hc-sr04": lazy(() => import("./elements/HcSr04")),
    "dht22": lazy(() => import("./elements/Dht22")),
    "mpu6050": lazy(() => import("./elements/Mpu6050")),
    "l298n": lazy(() => import("./elements/L298N")),
    "pnp-transistor": lazy(() => import("./elements/PnpTransistor")),
    "npn-transistor": lazy(() => import("./elements/NpnTransistor")),
    "diode": lazy(() => import("./elements/Diode")),
    "servo": lazy(() => import("./elements/Servo")),
    "dc-motor": lazy(() => import("./elements/DcMotor")),
    "hc05": lazy(() => import("./elements/Hc05")),
    "lcd-i2c": lazy(() => import("./elements/Lcdi2C")),
    "7-segment-display": lazy(() => import("./elements/7SegmentDisplay")),
    "micro-sd-card": lazy(() => import("./elements/MicroSdCard")),
    "push-button": lazy(() => import("./elements/PushButton")),
    "stepper-motor": lazy(() => import("./elements/StepperMotor")),
    "battery-9v": lazy(() => import("./elements/Battery9V")),
    "resistor": lazy(() => import("./elements/Resistor")),
    "led": lazy(() => import("./elements/Led")),
    "capacitor": lazy(() => import("./elements/Capacitor")),
    "pir-motion": lazy(() => import("./elements/PirMotion")),
    "photo-resistor": lazy(() => import("./elements/PhotoResistor")),
    "ssd1306": lazy(() => import("./elements/Ssd1306")),
    "ir-receiver": lazy(() => import("./elements/IrReceiver")),
    "tca9548a": lazy(() => import("./elements/Tca9548")),
    "ac-power-output": lazy(() => import("./elements/AcPowerOutput")),
    "soil-moisture-sensor": lazy(() => import("./elements/SoilMoistureSensor")),
    "pressure-sensor": lazy(() => import("./elements/PressureSensor")),
    "force-sensor-resistor": lazy(() => import("./elements/ForceSensorResistor")),
    "ftdi": lazy(() => import("./elements/Ftdi")),
    "inductor": lazy(() => import("./elements/Inductor")),
    "mosfet": lazy(() => import("./elements/Mosfet")),
    "nrf24l01": lazy(() => import("./elements/Nrf24L01")),
    "potentiometer": lazy(() => import("./elements/Potentiometer")),
    "sim800l": lazy(() => import("./elements/Sim800L")),
    "solenoid": lazy(() => import("./elements/Solenoid")),
    "bme280": lazy(() => import("./elements/Bme280")),
    "lm2596-boost-converter": lazy(() => import("./elements/Lm2596BoostConverter")),
    "lm2596-buck-converter": lazy(() => import("./elements/Lm2596BuckConverter")),
    "gps": lazy(() => import("./elements/Gps")),
    "as608-fingerprint-sensor": lazy(() => import("./elements/As608")),
    "relay-module": lazy(() => import("./elements/RelayModule")),
    "esp32-cam": lazy(() => import("./elements/Esp32Cam"))
};


