export const componentPins = {
  "esp32-devkit-v1": {
    "pins": ["VIN", "GND", "D13", "D12", "D14", "D27", "D26", "D25", "D33", "D32", "D35", "D34", "VN", "VP", "EN", "3V3", "GND", "D15", "D2", "D4", "RX2", "TX2", "D5", "D18", "D19", "D21", "RX0", "TX0", "D22", "D23"],
    "width": 107,
    "height": 200,
    "aliases": ["wifi", "bluetooth", "esp32", "esp32 devkit", "esp32 board", "esp32 development kit", "esp32 devkit v1", "microcontroller"],
    "description": "Wi-Fi and Bluetooth-enabled microcontroller board with dual-core processor, GPIO, ADC, PWM, and communication interfaces.",
    "category": "microcontroller",
    "typical_usage": "IoT, robotics, wireless control, sensor data collection.",
    "compatible_with": ["sensors", "actuators", "WiFi", "Bluetooth", "Arduino IDE"],
    "specs": "Operating voltage 3.3V, 30 GPIO pins, built-in Wi-Fi and Bluetooth."
  },
  "arduino-uno": {
    "pins": ["AREF", "GND", "D13", "D12", "D11", "D10", "D9", "D8", "D7", "D6", "D5", "D4", "D3", "D2", "TX0", "RX0", "IOREF", "RESET", "3.3V", "5V", "GND", "GND", "VIN", "A0", "A1", "A2", "A3", "A4", "A5"],
    "width": 290,
    "height": 213,
    "aliases": ["arduino", "uno", "arduino uno board", "arduino uno r3", "microcontroller"],
    "description": "Popular ATmega328P-based microcontroller board for embedded projects and prototyping.",
    "category": "microcontroller",
    "typical_usage": "Robotics, automation, learning electronics.",
    "compatible_with": ["shields", "sensors", "motors"],
    "specs": "5V logic, 14 digital I/O, 6 analog inputs, USB interface."
  },
  "buzzer": {
    "pins": ["GND", "VCC"],
    "width": 16,
    "height": 20,
    "aliases": ["buzzer module", "piezo buzzer", "active buzzer", "passive buzzer"],
    "description": "Audio signaling device that produces a tone when powered.",
    "category": "actuator",
    "typical_usage": "Alerts, alarms, status indicators, sound feedback.",
    "compatible_with": ["Arduino", "ESP32", "transistor driver circuits"],
    "specs": "Active buzzers operate with DC power; passive buzzers require PWM signal, 3-5V typical."
  },
  "analog-joystick": {
    "pins": ["VCC", "VERT", "HORZ", "SEL", "GND"],
    "width": 48,
    "height": 68,
    "aliases": ["joystick", "analog joystick module", "thumbstick"],
    "description": "Dual-axis joystick with potentiometers for X/Y movement and a push-button switch.",
    "category": "input device",
    "typical_usage": "Game controllers, robot steering, camera gimbals.",
    "compatible_with": ["Arduino", "ESP32", "ADC inputs"],
    "specs": "5V operating voltage, analog outputs for X/Y, digital output for button press."
  },
  "ds1307": {
    "pins": ["GND", "5V", "SDA", "SCL", "SQW", "RTC", "DS1307", "+"],
    "width": 26,
    "height": 22,
    "aliases": ["rtc", "ds1307 rtc", "real time clock", "rtc module"],
    "description": "Real-time clock module with backup battery for keeping accurate time.",
    "category": "sensor/module",
    "typical_usage": "Data logging, clocks, time-stamped systems.",
    "compatible_with": ["Arduino", "ESP32", "I2C devices"],
    "specs": "I2C interface, 5V logic, retains time with CR2032 coin cell."
  },
  "flame-sensor": {
    "pins": ["+", "-", "D", "A"],
    "width": 200,
    "height": 61.5,
    "aliases": ["flame detector", "fire sensor", "infrared flame sensor"],
    "description": "Infrared flame detector module that detects light emitted by fire.",
    "category": "sensor",
    "typical_usage": "Fire detection, safety systems, fire-fighting robots.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Operating voltage 3.3-5V, analog and digital outputs, detection angle < 60°."
  },
  "gas-sensor": {
    "pins": ["AOUT", "DOUT", "GND", "VCC", "PWR LED", "D0 LED"],
    "width": 137,
    "height": 62,
    "aliases": ["mq sensor", "gas detector", "gas sensor module"],
    "description": "Gas detection module using MQ series sensors for detecting gases like LPG, CO, and methane.",
    "category": "sensor",
    "typical_usage": "Air quality monitoring, gas leak detection, safety systems.",
    "compatible_with": ["Arduino", "ESP32", "analog input modules"],
    "specs": "5V operating voltage, analog and digital outputs, warm-up time ~20s."
  },
  "hc-sr04": {
    "pins": ["VCC", "TRIG", "ECHO", "GND"],
    "width": 45,
    "height": 26,
    "aliases": ["ultrasonic sensor", "hc sr04", "ultrasonic distance sensor"],
    "description": "Ultrasonic sensor for distance measurement using sound waves.",
    "category": "sensor",
    "typical_usage": "Obstacle detection, autonomous robots, parking sensors.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Operating voltage 5V, range 2cm-400cm, trigger/echo interface."
  },
  "dht22": {
    "pins": ["VCC", "DATA", "NC", "GND"],
    "width": 16,
    "height": 32,
    "aliases": ["dht22 sensor", "temperature humidity sensor", "am2302"],
    "description": "Digital temperature and humidity sensor providing calibrated output.",
    "category": "sensor",
    "typical_usage": "Weather stations, home automation, HVAC systems.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "3.3-6V supply, ±0.5°C accuracy, single-wire digital interface."
  },
  "mpu6050": {
    "pins": ["GND", "SCL", "SDA", "XDA", "XCL", "AD0", "INT", "VCC"],
    "width": 82,
    "height": 61,
    "aliases": ["mpu6050 sensor", "accelerometer gyroscope", "imu module"],
    "description": "6-axis accelerometer and gyroscope module for motion sensing.",
    "category": "sensor",
    "typical_usage": "IMUs, drones, gesture detection, robotics.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "I2C communication, 3-5V operation, 3-axis gyro + 3-axis accel."
  },
  "l298n": {
    "pins": ["OUT1", "OUT2", "OUT3", "OUT4", "5V", "GND", "12V", "5V", "ENA", "IN1", "IN2", "IN3", "IN4", "ENB", "5V"],
    "width": 138,
    "height": 136,
    "aliases": ["l298n motor driver", "h-bridge motor driver", "dual motor driver"],
    "description": "Dual H-bridge motor driver module that controls speed and direction of two DC motors.",
    "category": "motor driver",
    "typical_usage": "Line-following robots, RC cars, motor control.",
    "compatible_with": ["DC motors", "Arduino", "ESP32"],
    "specs": "5-35V motor supply, 2A per channel, TTL logic inputs."
  },
  "pnp-transistor": {
    "pins": ["B", "C", "E"],
    "width": 31,
    "height": 13,
    "aliases": ["pnp transistor", "pnp bjt"],
    "description": "BJT transistor type used for amplification or high-side switching; conducts when base is driven low.",
    "category": "active component",
    "typical_usage": "High-side load control, amplification stages, analog circuits.",
    "compatible_with": ["resistors", "microcontrollers", "relays"],
    "specs": "Collector current up to 100mA typical, gain (hFE) ≈ 100, base-emitter voltage ~0.7V."
  },
  "npn-transistor": {
    "pins": ["B", "C", "E"],
    "width": 31,
    "height": 13,
    "aliases": ["npn transistor", "npn bjt"],
    "description": "BJT transistor type used for amplification or switching; conducts when base is driven high.",
    "category": "active component",
    "typical_usage": "Switching loads, signal amplification, digital interfacing.",
    "compatible_with": ["resistors", "microcontrollers", "relays"],
    "specs": "Collector current up to 100mA typical, gain (hFE) ≈ 100, base-emitter voltage ~0.7V."
  },
  "diode": {
    "pins": ["-", "+"],
    "width": 27,
    "height": 6,
    "aliases": ["diode", "rectifier diode", "signal diode"],
    "description": "Semiconductor component that allows current to flow in one direction only, blocking reverse current.",
    "category": "active component",
    "typical_usage": "Rectification, reverse polarity protection, signal demodulation.",
    "compatible_with": ["power circuits", "transistors", "LEDs", "microcontrollers"],
    "specs": "Forward voltage drop ~0.7V (silicon), reverse voltage rating varies 20V-1000V+, current rating depends on type."
  },
  "servo": {
    "pins": ["GND", "VCC", "DATA"],
    "width": 170,
    "height": 66,
    "aliases": ["servo motor", "servo"],
    "description": "Rotational actuator that provides precise angular motion control.",
    "category": "actuator",
    "typical_usage": "Robotic arms, RC vehicles, steering mechanisms.",
    "compatible_with": ["Arduino", "ESP32", "PWM controllers"],
    "specs": "5V operating voltage, controlled via PWM signal."
  },
  "dc-motor": {
    "pins": ["+", "-"],
    "width": 71,
    "height": 58,
    "aliases": ["dc motor", "motor"],
    "description": "Two-wire brushed DC motor for continuous rotary motion.",
    "category": "actuator",
    "typical_usage": "Robot drive wheels, fans, pumps.",
    "compatible_with": ["L298N", "motor drivers", "power supplies"],
    "specs": "Operates 3-12V DC, speed proportional to voltage, current draw ~100-500mA."
  },
  "hc05": {
    "pins": ["KEY", "VCC", "GND", "TX", "RX", "State"],
    "width": 62,
    "height": 166,
    "aliases": ["hc05", "bluetooth module", "hc-05"],
    "description": "Bluetooth serial transceiver module for wireless communication.",
    "category": "communication module",
    "typical_usage": "Wireless control, data logging, IoT communication.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Bluetooth 2.0, 3.3V logic, UART interface, 9600 baud default."
  },
  "lcd-i2c": {
    "pins": ["GND", "VCC", "SDA", "SCL"],
    "width": 254,
    "height": 114,
    "aliases": ["i2c lcd", "lcd display", "16x2 lcd i2c"],
    "description": "16x2 character LCD display module using I2C interface.",
    "category": "display",
    "typical_usage": "Displaying text, sensor data, menus.",
    "compatible_with": ["Arduino", "ESP32", "I2C devices"],
    "specs": "5V supply, I2C communication via SDA/SCL, 16x2 characters."
  },
  "micro-sd-card": {
    "pins": ["CD", "DO", "GND", "SCK", "VCC", "DI", "CS"],
    "width": 65,
    "height": 62,
    "aliases": ["micro sd module", "sd card reader", "sd card module"],
    "description": "MicroSD card reader module for data logging and file storage.",
    "category": "storage module",
    "typical_usage": "Data logging, audio playback, file storage in embedded systems.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Supports SPI interface, 3.3V logic, up to 32GB cards (FAT32)."
  },
  "push-button": {
    "pins": ["1", "2"],
    "width": 18,
    "height": 12,
    "aliases": ["push button", "tactile switch", "momentary switch"],
    "description": "Momentary switch that closes the circuit when pressed.",
    "category": "input device",
    "typical_usage": "User input, reset buttons, control panels.",
    "compatible_with": ["Arduino", "ESP32", "pull-up resistors"],
    "specs": "Normally open contact, rated for 3.3-5V logic, mechanical life >100k presses."
  },
  "7-segment-display": {
    "pins": ["b", "a", "com", "f", "g", "DP", "c", "com1", "d", "e"],
    "width": 36,
    "height": 66,
    "aliases": ["7 segment", "seven segment display", "7seg display"],
    "description": "LED display for showing numerical digits using seven light segments.",
    "category": "display",
    "typical_usage": "Digital counters, clocks, numeric indicators.",
    "compatible_with": ["Arduino", "ESP32"],
    "specs": "Common anode or cathode variants, 2V forward voltage per segment."
  },
  "stepper-motor": {
    "pins": ["1", "2", "3", "4"],
    "width": 217,
    "height": 237,
    "aliases": ["stepper motor", "bipolar stepper", "unipolar stepper"],
    "description": "Electromechanical motor that rotates in precise steps for accurate position control.",
    "category": "actuator",
    "typical_usage": "CNC machines, 3D printers, robotic arms.",
    "compatible_with": ["ULN2003 driver", "A4988", "L298N"],
    "specs": "4-wire (bipolar) or 5-wire (unipolar), step angle typically 1.8°."
  },
  "battery-9v": {
    "pins": ["VCC", "GND"],
    "width": 59,
    "height": 115,
    "aliases": ["9v battery", "battery", "9 volt battery"],
    "description": "9V battery used as portable DC power supply for small electronics.",
    "category": "power source",
    "typical_usage": "Prototyping, battery-powered circuits.",
    "compatible_with": ["Arduino", "L298N", "sensors"],
    "specs": "Nominal voltage 9V, typical capacity 500mAh."
  },
  "resistor": {
    "pins": ["1", "2"],
    "width": 36,
    "height": 7,
    "aliases": ["resistor", "ohm resistor"],
    "description": "Passive component that limits current and divides voltage.",
    "category": "passive component",
    "typical_usage": "LED protection, biasing circuits, pull-up resistors.",
    "compatible_with": ["LEDs", "transistors", "ICs"],
    "specs": "Available in various resistances, 0.25W typical rating."
  },
  "led": {
    "pins": ["+", "-"],
    "width": 16,
    "height": 30,
    "aliases": ["led", "light emitting diode"],
    "description": "Light-emitting diode that glows when current flows through it.",
    "category": "indicator",
    "typical_usage": "Status indicators, displays, lighting.",
    "compatible_with": ["resistors", "transistors", "microcontrollers"],
    "specs": "Forward voltage ~2V, current ~20mA, polarity sensitive."
  },
  "capacitor": {
    "pins": ["+", "-"],
    "width": 28,
    "height": 52,
    "aliases": ["capacitor", "electrolytic capacitor", "ceramic capacitor"],
    "description": "Passive component that stores and releases electrical energy as charge across two plates.",
    "category": "passive component",
    "typical_usage": "Power supply filtering, signal coupling, timing circuits.",
    "compatible_with": ["resistors", "microcontrollers", "power circuits"],
    "specs": "Available in ceramic, electrolytic, and film types; voltage ratings vary from 6.3V to 50V+."
  },
  "pir-motion": {
    "pins": ["-", "D", "+"],
    "width": 91,
    "height": 92,
    "aliases": ["pir sensor", "motion detector", "pir motion sensor"],
    "description": "Infrared motion sensor that detects human movement based on body heat.",
    "category": "sensor",
    "typical_usage": "Security systems, automatic lighting, motion-triggered devices.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Operating voltage 5V, digital output, detection range up to 7 meters."
  },
  "photo-resistor": {
    "pins": ["A0", "D0", "GND", "VCC"],
    "width": 174,
    "height": 62,
    "aliases": ["ldr", "light sensor", "photoresistor", "light dependent resistor"],
    "description": "Light-dependent resistor (LDR) sensor module that changes resistance based on ambient light intensity.",
    "category": "sensor",
    "typical_usage": "Automatic lighting, light intensity monitoring, obstacle detection in robots.",
    "compatible_with": ["Arduino", "ESP32", "analog input modules"],
    "specs": "Operating voltage 3.3-5V, analog output proportional to light level, optional digital output with adjustable threshold."
  },
  "ssd1306": {
    "pins": ["SDA", "SCL", "VCC", "GND"],
    "width": 148,
    "height": 114,
    "aliases": ["oled display", "ssd1306", "i2c oled"],
    "description": "0.96-inch OLED display using I2C communication for text or graphics.",
    "category": "display",
    "typical_usage": "Compact UI display for IoT and embedded systems.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "3.3-5V, I2C protocol, 128x64 pixels."
  },
  "ir-receiver": {
    "pins": ["D", "VCC", "GND"],
    "width": 61,
    "height": 71,
    "aliases": ["ir receiver", "infrared sensor", "remote receiver"],
    "description": "Infrared receiver module for detecting remote control signals.",
    "category": "sensor",
    "typical_usage": "Remote control systems, IR communication, consumer electronics.",
    "compatible_with": ["Arduino", "ESP32", "TV remotes"],
    "specs": "Operating voltage 3.3-5V, demodulated digital output, typically 38kHz carrier frequency."
  },
  "tca9548a": {
    "pins": ["VIN", "GND", "SDA", "SCL", "RST", "A0", "A1", "A2", "SD0", "SC0", "SD1", "SC1", "SC7", "SD7", "SC6", "SD6", "SC5", "SD5", "SC4", "SD4", "SC3", "SD3", "SC2", "SD2"],
    "width": 97,
    "height": 165,
    "aliases": ["I2C multiplexer", "8-channel I2C switch", "TCA9548A module"],
    "description": "An 8-channel I²C multiplexer that allows multiple I²C devices with the same address to connect to one microcontroller bus.",
    "category": "interface",
    "typical_usage": "Connecting multiple I²C sensors or modules with identical addresses to a single controller such as Arduino, ESP32, or Raspberry Pi.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi", "STM32"],
    "specs": "Operating voltage 1.65-5.5V, 8 independent downstream I²C channels, I²C address configurable via A0-A2 pins (0x70-0x77), bidirectional signal switching, 400kHz I²C speed supported."
  },
  "ac-power-output": {
    "pins": ["LIVE", "GND"],
    "width": 70,
    "height": 55,
    "aliases": ["alternate current", "power", "ac", "ac output", "relay output", "mains control", "high voltage output"],
    "description": "Relay-based AC power output module that allows a low-voltage microcontroller to safely switch high-voltage AC loads.",
    "category": "power control",
    "typical_usage": "Controlling AC appliances such as lights, fans, pumps, and sockets using microcontrollers.",
    "compatible_with": [],
    "specs": "AC load up to 250VAC @ 10A, opto-isolated input recommended for safety."
  },
  "soil-moisture-sensor": {
    "width": 99.379,
    "height": 196.169,
    "pins": ["OUT", "GND", "VCC"],
    "aliases": ["Hygrometer", "Corrosion-resistant soil sensor", "Capacitive soil sensor"],
    "description": "A sensor that measures the volumetric water content in soil based on dielectric permittivity.",
    "category": "sensor",
    "typical_usage": "Automated irrigation systems, plant monitoring, and smart gardening projects.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi", "STM32"],
    "specs": "Operating voltage 3.3V-5V, Analog output voltage 0-3V DC, capacitive sensing technology."
  },
  "pressure-sensor": {
    "width": 72,
    "height": 78.720,
    "pins": ["DRDY", "CSB", "MISO", "MOSI", "SCK", "3.3V", "GND"],
    "aliases": ["Barometric pressure sensor", "Altimeter", "Digital pressure module"],
    "description": "A high-precision digital pressure sensor capable of measuring atmospheric pressure and altitude.",
    "category": "sensor",
    "typical_usage": "Weather stations, drone altitude hold, and indoor navigation.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Interface: SPI/I2C, Pressure range 300-1100 hPa, Accuracy ±0.12 hPa (equivalent to ±1m altitude)."
  },
  "force-sensor-resistor": {
    "width": "67.200",
    "height": "209.760",
    "pins": ["1", "2"],
    "aliases": ["FSR", "Pressure pad", "Force sensitive resistor"],
    "description": "A polymer thick film (PTF) device which exhibits a decrease in resistance with an increase in the force applied to the active surface.",
    "category": "sensor",
    "typical_usage": "Human-machine interfaces, musical instruments, and weight detection triggers.",
    "compatible_with": ["Arduino", "ESP32", "Analog-to-Digital Converters"],
    "specs": "Force sensitivity range ~0.2N to 20N, Non-linear resistance response."
  },
  "ftdi": {
    "width": "103.899",
    "height": "57.600",
    "pins": ["DTR", "RX", "TX", "POWER", "CTS", "GND"],
    "aliases": ["USB to TTL converter", "Serial adapter", "FT232RL breakout"],
    "description": "A USB-to-serial UART interface board used to program or communicate with microcontrollers that lack a built-in USB port.",
    "category": "interface",
    "typical_usage": "Programming Arduino Pro Mini, ESP-01, or debugging serial output via PC.",
    "compatible_with": ["PC", "Arduino Pro Mini", "ESP8266"],
    "specs": "USB 2.0 compatible, Support for 3.3V and 5V logic levels, Integrated EEPROM."
  },
  "inductor": {
    "width": "41.119",
    "height": "16.917",
    "pins": ["1", "2"],
    "aliases": ["Choke", "Coil", "Reactor"],
    "description": "A passive two-terminal electrical component that stores energy in a magnetic field when electric current flows through it.",
    "category": "passive",
    "typical_usage": "DC-DC converters, filtering noise in power supplies, and radio frequency circuits.",
    "compatible_with": ["All DC and AC circuits"],
    "specs": "Inductance measured in Henries (H), Current rating depends on wire gauge and core material."
  },
  "mosfet": {
    "width": "35.518",
    "height": "59.824",
    "pins": ["G", "D", "S"],
    "aliases": ["Transistor", "N-Channel MOSFET", "Logic level MOSFET"],
    "description": "A type of field-effect transistor used for switching or amplifying electronic signals.",
    "category": "semiconductor",
    "typical_usage": "PWM motor control, high-power LED switching, and relay replacement.",
    "compatible_with": ["Arduino", "ESP32", "PWM controllers"],
    "specs": "Drain-Source Voltage (Vds), Gate Threshold Voltage (Vgs), Continuous Drain Current (Id)."
  },
  "nrf24l01": {
    "width": "126.918",
    "height": "63.000",
    "pins": ["MISO", "SCK", "CE", "GND", "IRQ", "MOSI", "CSN", "VCC"],
    "aliases": ["RF module", "Wireless transceiver", "2.4GHz radio"],
    "description": "A low-power 2.4GHz wireless transceiver module for point-to-point or mesh network communication.",
    "category": "communication",
    "typical_usage": "Remote control systems, wireless sensor networks, and IoT telemetry.",
    "compatible_with": ["Arduino", "Raspberry Pi", "STM32"],
    "specs": "2.4GHz ISM band, 250kbps to 2Mbps data rates, Operating voltage 1.9V-3.6V (IO is 5V tolerant)."
  },
  "potentiometer": {
    "width": "38.919",
    "height": "79.665",
    "pins": ["VCC", "OUT", "GND"],
    "aliases": ["Variable resistor", "Pot", "Trimmer"],
    "description": "A three-terminal resistor with a sliding or rotating contact that forms an adjustable voltage divider.",
    "category": "passive",
    "typical_usage": "Volume control, user input tuning, and adjusting LCD contrast.",
    "compatible_with": ["Arduino", "Any Analog Input"],
    "specs": "Standard resistance values (10k, 100k ohm), Linear or Logarithmic taper."
  },
  "sim800l": {
    "width": "90.715",
    "height": "117.065",
    "pins": ["5V", "GND", "VDD", "TX", "RX", "GND", "RST"],
    "aliases": ["GSM module", "GPRS module", "Cellular breakout"],
    "description": "A miniature cellular module that allows for GPRS transmission, sending/receiving SMS, and making/receiving voice calls.",
    "category": "communication",
    "typical_usage": "Remote SMS alerts, GPS trackers, and cellular IoT nodes.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Quad-band 850/900/1800/1900MHz, Operating voltage 3.7V-4.2V (requires high peak current)."
  },
  "solenoid": {
    "width": "63.072",
    "height": "150.193",
    "pins": ["-", "+"],
    "aliases": ["Electromagnetic actuator", "Solenoid valve", "Push-pull solenoid"],
    "description": "A coil of wire that acts as a magnet while carrying electric current, typically used to move a plunger.",
    "category": "actuator",
    "typical_usage": "Electronic door locks, automated valves, and robotic tapping.",
    "compatible_with": ["Relays", "MOSFET switches"],
    "specs": "Operating voltage (6V, 12V, or 24V), Stroke length, Holding force."
  },
  "bme280": {
    "width": "36.000",
    "height": "57.600",
    "pins": ["GND", "3.3V", "SDA", "SCK"],
    "aliases": ["Environmental sensor", "Temp-Humidity-Pressure sensor"],
    "description": "An integrated environmental sensor that measures temperature, humidity, and barometric pressure.",
    "category": "sensor",
    "typical_usage": "Smart home climate control, weather stations, and indoor air quality monitoring.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "I2C/SPI interface, Temp range -40 to +85°C, Humidity 0-100%, Pressure 300-1100hPa."
  },

  "lm2596-boost-converter": {
    "width": "157.500",
    "height": "72.000",
    "pins": ["IN+", "OUT+", "OUT-", "IN-"],
    "aliases": ["Step-up converter", "DC-DC boost module", "XL6009 module"],
    "description": "A DC-DC power module that steps up an input voltage to a higher output voltage using a switching regulator.",
    "category": "power",
    "typical_usage": "Powering 12V devices from a 5V USB source or increasing battery voltage for motors.",
    "compatible_with": ["Batteries", "Solar panels", "DC Power supplies"],
    "specs": "Input 3V-32V, Output 5V-35V (adjustable via potentiometer), Max current 3A, switching frequency 400kHz."
  },
  "lm2596-buck-converter": {
    "width": "157.500",
    "height": "72.000",
    "pins": ["IN+", "OUT+", "OUT-", "IN-"],
    "aliases": ["Step-down converter", "DC-DC buck module", "Adjustable voltage regulator"],
    "description": "An efficient switching regulator that steps down a higher DC input voltage to a lower regulated DC output voltage.",
    "category": "power",
    "typical_usage": "Dropping a 12V battery to 5V for an Arduino or a 24V supply to 12V for fans.",
    "compatible_with": ["Arduino", "Raspberry Pi", "LED strips", "CCTV cameras"],
    "specs": "Input 4.5V-40V, Output 1.23V-37V, Max current 3A, Efficiency up to 92%."
  },
  "gps": {
    "width": "115.000",
    "height": "151.000",
    "pins": ["VCC", "RX", "TX", "GND"],
    "aliases": ["GPS Module", "NEO-6M", "Satellite positioning module"],
    "description": "A Global Positioning System receiver that provides longitude, latitude, altitude, and time data via serial communication.",
    "category": "sensor",
    "typical_usage": "Asset tracking, drone navigation, and time synchronization for remote data loggers.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi", "STM32"],
    "specs": "NMEA protocol output, Baud rate 9600 (typical), Ceramic antenna included, Position accuracy 2.5m."
  },
  "as608-fingerprint-sensor": {
    "width": "71",
    "height": "147",
    "pins": ["VCC", "GND", "TX", "RX", "3.3V"],
    "aliases": ["Optical fingerprint module", "Biometric sensor"],
    "description": "An optical fingerprint sensor with an onboard high-speed DSP chip for image rendering, calculation, and template matching.",
    "category": "sensor",
    "typical_usage": "Biometric door locks, attendance systems, and secure device authentication.",
    "compatible_with": ["Arduino", "ESP32", "PC via FTDI"],
    "specs": "Storage capacity 162-1000 templates, UART interface, False Acceptance Rate (FAR) <0.001%."
  },
  "relay-module": {
    "width": "50.000",
    "height": "70.000",
    "pins": ["VCC", "GND", "IN", "NC", "NO"],
    "aliases": ["5V Relay", "Single channel relay", "Electromagnetic switch"],
    "description": "A module used to control high-voltage/high-current devices like AC appliances using low-voltage digital signals.",
    "category": "actuator",
    "typical_usage": "Home automation, switching lights, heaters, or water pumps.",
    "compatible_with": ["Arduino", "ESP32", "Raspberry Pi"],
    "specs": "Switching capacity 10A at 250VAC/30VDC, Logic level trigger 5V (Active Low/High depending on jumper)."
  },
  "esp32-cam": {
    "width": "975.200",
    "height": "698.400",
    "pins": ["14", "13", "16", "12", "5V", "3.3V", "15", "GND", "0", "4", "2", "VCC", "U0T", "U0R", "GND2", "GND1"],
    "aliases": ["ESP-32CAM", "AI-Thinker Cam", "WiFi Camera Module"],
    "description": "A small-form factor camera module based on the ESP32 chip with an OV2640 camera, microSD card slot, and built-in WiFi/Bluetooth.",
    "category": "microcontroller",
    "typical_usage": "Face recognition, QR code reading, wireless surveillance, and IoT image uploads.",
    "compatible_with": ["FTDI Adapter (for programming)", "Arduino IDE", "MicroPython"],
    "specs": "Dual-core 32-bit CPU, 520 KB SRAM + 4MB PSRAM, OV2640 camera support, integrated Flash LED."
  },
  "franzininho": {
    "pins": ["GND", "VCC", "5", "4", "3", "2", "1", "0", "VIN", "GND", "VCC"],
    "width": 242,
    "height": 113,
    "aliases": ["franzininho", "franzininho board", "franzininho mini", "franzininho mini board", "microcontroller"],
    "description": "A small-form factor microcontroller board based on the ESP32 chip with an OV2640 camera, microSD card slot, and built-in WiFi/Bluetooth.",
    "category": "microcontroller",
    "typical_usage": "IoT projects, home automation, robotics, and other small-form factor projects.",
    "compatible_with": ["FTDI Adapter (for programming)", "Arduino IDE", "MicroPython"],
    "specs": "Dual-core 32-bit CPU, 520 KB SRAM + 4MB PSRAM, OV2640 camera support, integrated Flash LED."
  },
}

