import re
import json
import ast
from typing import Optional, Dict, Any

def extract_json_array(text: str) -> Optional[str]:
    """Extracts a JSON array from a string using regex."""
    pattern = r'(\[.*?\])'
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(0)
    return None

def extract_json_object(text: str) -> Optional[Dict[str, Any]]:
    """Extracts a JSON object from a string using regex and handles nested structures."""
    # Using a slightly more robust regex approach similar to the original notebook
    text = text.replace("```json\n", '', 1).replace('```', '')
    
    # Try to find the first { and last }
    start = text.find('{')
    end = text.rfind('}')
    
    if start != -1 and end != -1:
        json_str = text[start:end+1]
        
        # Clean up common LLM JSON errors before parsing
        # Remove block comments /* ... */
        json_str = re.sub(r'/\*.*?\*/', '', json_str, flags=re.DOTALL)
        # Remove single line comments // ...
        json_str = re.sub(r'//.*', '', json_str)
        # Remove trailing commas before closing braces/brackets
        json_str = re.sub(r',\s*}', '}', json_str)
        json_str = re.sub(r',\s*\]', ']', json_str)

        try:
            parsed_json = json.loads(json_str)
        except json.JSONDecodeError:
            # Fallback to ast if json fails (sometimes LLMs output single quotes)
            try:
                parsed_json = ast.literal_eval(json_str)
            except:
                return json_str  # Return the faulty string instead of None
        
        # Flatten nested path arrays in connections generated by some LLMs
        if isinstance(parsed_json, dict) and "connections" in parsed_json:
            for conn in parsed_json["connections"]:
                if len(conn) >= 4 and isinstance(conn[3], list):
                    flat_path = []
                    for segment in conn[3]:
                        if isinstance(segment, list):
                            flat_path.extend(segment)
                        else:
                            flat_path.append(segment)
                    conn[3] = flat_path
                    
        return parsed_json

    return text  # Return the original entire text instead of None if no JSON brackets found

def parse_extracted_components(text: str) -> list[str]:
    """Parses a string that is expected to contain a JSON array of component names."""
    parsed = extract_json_array(text)
    if parsed:
        try:
            return ast.literal_eval(parsed)
        except:
            # If ast fails, try to split by commas/newlines if it looks like a list
            return [line.strip("- *") for line in text.split("\n") if line.strip()]
    return [text.strip()]
